version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    env_file: ./.env

  tables_backend:
    build: ./
    restart: always
    command: sh -c "python manage.py migrate"
    depends_on:
      - db
    env_file: ./.env
    ports:
      - "8000:8000"

volumes:
  db: