# Generated by Django 4.2.1 on 2023-05-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('distance', models.IntegerField(verbose_name='Расстояние')),
            ],
        ),
    ]
